/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Daniel Sanz Ferrer
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/vista/images/logo600x600.png"));
        JLabel backgroundLabel = new JLabel(backgroundImage);
        backgroundLabel.setBounds(0, 0, backgroundImage.getIconWidth(), backgroundImage.getIconHeight());
        jDesktopPaneEscritorio.add(backgroundLabel);
        jDesktopPaneEscritorio.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                backgroundLabel.setSize(jDesktopPaneEscritorio.getSize());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProveedores = new javax.swing.JMenu();
        jMenuArticulos = new javax.swing.JMenu();
        jMenuPedidos = new javax.swing.JMenu();
        jMenuAuditoria = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/proveedores.png"))); // NOI18N
        jMenuProveedores.setText("Proveedores");
        jMenuProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProveedoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuProveedores);

        jMenuArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/articulos.png"))); // NOI18N
        jMenuArticulos.setText("Artículos");
        jMenuArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuArticulosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuArticulos);

        jMenuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/pedidos.png"))); // NOI18N
        jMenuPedidos.setText("Pedidos");
        jMenuPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPedidosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPedidos);

        jMenuAuditoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/auditoria.png"))); // NOI18N
        jMenuAuditoria.setText("Auditoría Artículos");
        jMenuAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAuditoriaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAuditoria);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/salir.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProveedoresMouseClicked
        VistaProveedor pro = new VistaProveedor();
        jDesktopPaneEscritorio.add(pro);
        //Obtener el tamaño del JDesktopPane y el tamaño de la ventana
        int x = (jDesktopPaneEscritorio.getWidth() - pro.getWidth()) / 2;
        int y = (jDesktopPaneEscritorio.getHeight() - pro.getHeight()) / 2;
        pro.setLocation(x, y);
        pro.setVisible(true);
    }//GEN-LAST:event_jMenuProveedoresMouseClicked

    private void jMenuArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuArticulosMouseClicked
        VistaArticulo art = new VistaArticulo();
        jDesktopPaneEscritorio.add(art);
        int x = (jDesktopPaneEscritorio.getWidth() - art.getWidth()) / 2;
        int y = (jDesktopPaneEscritorio.getHeight() - art.getHeight()) / 2;
        art.setLocation(x, y);
        art.setVisible(true);
    }//GEN-LAST:event_jMenuArticulosMouseClicked

    private void jMenuPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPedidosMouseClicked
        VistaContenido con = new VistaContenido();
        jDesktopPaneEscritorio.add(con);
        int x = (jDesktopPaneEscritorio.getWidth() - con.getWidth()) / 2;
        int y = (jDesktopPaneEscritorio.getHeight() - con.getHeight()) / 2;
        con.setLocation(x, y);
        con.setVisible(true);
    }//GEN-LAST:event_jMenuPedidosMouseClicked

    private void jMenuAuditoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAuditoriaMouseClicked
        VistaAuditoria au = new VistaAuditoria();
        jDesktopPaneEscritorio.add(au);
        int x = (jDesktopPaneEscritorio.getWidth() - au.getWidth()) / 2;
        int y = (jDesktopPaneEscritorio.getHeight() - au.getHeight()) / 2;
        au.setLocation(x, y);
        au.setVisible(true);
    }//GEN-LAST:event_jMenuAuditoriaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenu jMenuArticulos;
    private javax.swing.JMenu jMenuAuditoria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuPedidos;
    private javax.swing.JMenu jMenuProveedores;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
