/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.util.EventObject;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import modelo.ProveedorControl;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Daniel Sanz Ferrer
 */
public class VistaProveedor extends javax.swing.JInternalFrame {

    private final ProveedorControl PROCON = new ProveedorControl();
    private String nombre, email, web, nombreAnt;
    private double descuento;
    private int numCliente;

    /**
     * Creates new form FrmCategoria
     */
    public VistaProveedor() {
        initComponents();
        jTabbedPaneProveedores.setEnabledAt(1, false);
        int total = PROCON.total();
        mostrarPaginas();
        jTableProveedores.setModel(PROCON.listar("", 10, 1));
        listar();
        int mostrados = PROCON.totalMostrados();
        jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProveedores = new javax.swing.JTabbedPane();
        jPanelListado = new javax.swing.JPanel();
        jLabelNombreBuscar = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelNumPagina = new javax.swing.JLabel();
        jComboBoxPagina = new javax.swing.JComboBox<>();
        jLabelTotal = new javax.swing.JLabel();
        jComboBoxRegistrosPagina = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jPanelMantenimiento = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombreMantenimiento = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelNota = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelPagina = new javax.swing.JLabel();
        jTextFieldPagina = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelDescuento = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabelNoCliente = new javax.swing.JLabel();
        jTextFieldNoCliente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proveedores");

        jLabelNombreBuscar.setText("Proveedor:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Correo Electrónico", "Página Web", "Descuento %", "Número de Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProveedores);

        jLabelNumPagina.setText("# Página");

        jComboBoxPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaginaActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total de proveedores por página");

        jComboBoxRegistrosPagina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "25", "50", "100" }));
        jComboBoxRegistrosPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRegistrosPaginaActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListadoLayout = new javax.swing.GroupLayout(jPanelListado);
        jPanelListado.setLayout(jPanelListadoLayout);
        jPanelListadoLayout.setHorizontalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanelListadoLayout.createSequentialGroup()
                                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                                        .addComponent(jLabelNombreBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonEditar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEliminar)
                                .addGap(0, 253, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelListadoLayout.createSequentialGroup()
                        .addComponent(jLabelNumPagina)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRegistrosPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanelListadoLayout.setVerticalGroup(
            jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreBuscar)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonEditar)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumPagina)
                    .addComponent(jComboBoxPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal)
                    .addComponent(jComboBoxRegistrosPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneProveedores.addTab("Listado", jPanelListado);

        jPanelMantenimiento.setEnabled(false);
        jPanelMantenimiento.setFocusable(false);
        jPanelMantenimiento.setRequestFocusEnabled(false);

        jLabelNombre.setText("Nombre (*)");

        jLabelCorreo.setText("Correo Electrónico (*)");

        jLabelNota.setText("(*) Indica que es un campo obligatorio.");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelPagina.setText("Página Web (*)");

        jLabelDescuento.setText("Descuento (*)");

        jLabelNoCliente.setText("Número de Cliente (*)");

        javax.swing.GroupLayout jPanelMantenimientoLayout = new javax.swing.GroupLayout(jPanelMantenimiento);
        jPanelMantenimiento.setLayout(jPanelMantenimientoLayout);
        jPanelMantenimientoLayout.setHorizontalGroup(
            jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMantenimientoLayout.createSequentialGroup()
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCorreo)
                            .addComponent(jLabelPagina)
                            .addComponent(jLabelDescuento)
                            .addComponent(jLabelNoCliente))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jTextFieldPagina)
                            .addComponent(jTextFieldCorreo)
                            .addComponent(jTextFieldDescuento)
                            .addComponent(jTextFieldNoCliente)))
                    .addGroup(jPanelMantenimientoLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNota)
                            .addGroup(jPanelMantenimientoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButtonGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVolver)))))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanelMantenimientoLayout.setVerticalGroup(
            jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombreMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreo)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPagina)
                    .addComponent(jTextFieldPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescuento)
                    .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoCliente)
                    .addComponent(jTextFieldNoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNota)
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonVolver))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPaneProveedores.addTab("Mantenimiento", jPanelMantenimiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProveedores)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProveedores)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String nombre = jTextFieldNombre.getText();
        int regPag = Integer.valueOf(jComboBoxRegistrosPagina.getItemAt(jComboBoxRegistrosPagina.getSelectedIndex()));
        int total = PROCON.total();
        jTableProveedores.setModel(PROCON.listar(nombre, regPag, 1));
        listar();
        jTextFieldNombre.setText("");
        int mostrados = PROCON.totalMostrados();
        jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores.");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        jTextFieldNombreMantenimiento.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldPagina.setText("");
        jTextFieldDescuento.setText("");
        jTextFieldNoCliente.setText("");       
        jButtonGuardar.setText("Guardar");
        jTabbedPaneProveedores.setSelectedIndex(1);
        jTabbedPaneProveedores.setEnabledAt(0, false);
        jTabbedPaneProveedores.setEnabledAt(1, true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (jTableProveedores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione el proveedor a editar.", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jButtonGuardar.setText("Editar");
            int filaSeleccionada = jTableProveedores.getSelectedRow();
            Object nombre2 = jTableProveedores.getValueAt(filaSeleccionada, 0);
            Object email2 = jTableProveedores.getValueAt(filaSeleccionada, 1);
            Object web2 = jTableProveedores.getValueAt(filaSeleccionada, 2);
            Object descuento2 = jTableProveedores.getValueAt(filaSeleccionada, 3);
            Object numCliente2 = jTableProveedores.getValueAt(filaSeleccionada, 4);
            this.nombreAnt = String.valueOf(nombre2);
            this.email = String.valueOf(email2);
            this.web = String.valueOf(web2);
            this.descuento = Double.valueOf(String.valueOf(descuento2));
            this.numCliente = Integer.valueOf(String.valueOf(numCliente2));
            jTextFieldNombreMantenimiento.setText(nombreAnt);
            jTextFieldCorreo.setText(String.valueOf(email));
            jTextFieldPagina.setText(String.valueOf(web));
            jTextFieldDescuento.setText(String.valueOf(descuento));
            jTextFieldNoCliente.setText(String.valueOf(numCliente));
            jTabbedPaneProveedores.setSelectedIndex(1);
            jTabbedPaneProveedores.setEnabledAt(0, false);
            jTabbedPaneProveedores.setEnabledAt(1, true);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        if (jButtonGuardar.getText().equals("Guardar")) {
            if (jTextFieldNombreMantenimiento.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir un nombre de proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldCorreo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir el correo electrónico del proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldPagina.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir la página web del proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldDescuento.getText().equals("") || !jTextFieldDescuento.getText().matches("^[0-9]{1,2}([.][0-9]{1,2})?$")) {
                JOptionPane.showMessageDialog(null, "Debes introducir el descuento que el proveedor ofrece en formato válido.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldNoCliente.getText().equals("") || !jTextFieldNoCliente.getText().matches("^\\d+$")) {
                JOptionPane.showMessageDialog(null, "Debes introducir un número de cliente válido asociado al proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else {
                asignarValores();
                String resultado = PROCON.insertar(nombre, email, web, descuento, numCliente);
                if (resultado.equals("OK")) {
                    JOptionPane.showMessageDialog(null, "Proveedor insertado correctamente.", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
                    vaciarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, resultado, "Proveedores", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            if (jTextFieldNombreMantenimiento.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir un nombre de proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldCorreo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir el correo electrónico del proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldPagina.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debes introducir la página web del proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldDescuento.getText().equals("") || !jTextFieldDescuento.getText().matches("^[0-9]{1,2}([.][0-9]{1,2})?$")) {
                JOptionPane.showMessageDialog(null, "Debes introducir el descuento que el proveedor ofrece en formato válido.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else if (jTextFieldNoCliente.getText().equals("") || !jTextFieldNoCliente.getText().matches("^\\d+$")) {
                JOptionPane.showMessageDialog(null, "Debes introducir un número de cliente válido asociado al proveedor.", "Proveedores", JOptionPane.WARNING_MESSAGE);
            } else {
                asignarValores();
                String resultado = PROCON.actualizar(nombre, nombreAnt, email, web, descuento, numCliente);
                if (resultado.equals("OK")) {
                    JOptionPane.showMessageDialog(null, "Proveedor actualizado correctamente.", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, resultado, "Proveedores", JOptionPane.ERROR_MESSAGE);
                }
                jTabbedPaneProveedores.setSelectedIndex(0);
                jTabbedPaneProveedores.setEnabledAt(0, true);
                jTabbedPaneProveedores.setEnabledAt(1, false);
                int total = PROCON.total();
                jTableProveedores.setModel(PROCON.listar("", 10, 1));
                listar();
                jComboBoxPagina.setSelectedIndex(0);
                jComboBoxRegistrosPagina.setSelectedIndex(0);
                int mostrados = PROCON.totalMostrados();
                jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores");
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        jTabbedPaneProveedores.setSelectedIndex(0);
        jTabbedPaneProveedores.setEnabledAt(0, true);
        jTabbedPaneProveedores.setEnabledAt(1, false);
        jTextFieldNombre.setText("");
        int total = PROCON.total();
        jTableProveedores.setModel(PROCON.listar("", 10, 1));
        listar();
        int mostrados = PROCON.totalMostrados();
        jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores");
        jComboBoxPagina.setSelectedIndex(0);
        jComboBoxRegistrosPagina.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jComboBoxRegistrosPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRegistrosPaginaActionPerformed
        jComboBoxPagina.setModel(new DefaultComboBoxModel<>());
        int regPag = Integer.valueOf(jComboBoxRegistrosPagina.getItemAt(jComboBoxRegistrosPagina.getSelectedIndex()));
        int total = PROCON.total();
        mostrarPaginas();
        jTableProveedores.setModel(PROCON.listar("", regPag, 1));
        listar();
        int mostrados = PROCON.totalMostrados();
        jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores");
    }//GEN-LAST:event_jComboBoxRegistrosPaginaActionPerformed

    private void jComboBoxPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaginaActionPerformed
        int regPag = Integer.valueOf(jComboBoxRegistrosPagina.getItemAt(jComboBoxRegistrosPagina.getSelectedIndex()));
        int pag = Integer.valueOf(jComboBoxPagina.getItemAt(jComboBoxPagina.getSelectedIndex()));
        int total = PROCON.total();
        jTableProveedores.setModel(PROCON.listar("", regPag, pag));
        listar();
        int mostrados = PROCON.totalMostrados();
        jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores");
    }//GEN-LAST:event_jComboBoxPaginaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if (jTableProveedores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione el proveedor a eliminar.", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int filaSeleccionada = jTableProveedores.getSelectedRow();
            Object pro = jTableProveedores.getValueAt(filaSeleccionada, 0);
            String prov = String.valueOf(pro);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas eliminar el proveedor " + prov + "?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                String delete = PROCON.eliminar(prov);
                if (delete.equals("OK")) {
                    JOptionPane.showMessageDialog(null, "Eliminación del proveedor " + prov + " realizada con éxito.", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, delete, "Proveedores", JOptionPane.ERROR_MESSAGE);
                }
                int total = PROCON.total();
                jTableProveedores.setModel(PROCON.listar("", 10, 1));
                listar();
                jComboBoxPagina.setSelectedIndex(0);
                jComboBoxRegistrosPagina.setSelectedIndex(0);
                int mostrados = PROCON.totalMostrados();
                jLabelCantidad.setText("Mostrando " + mostrados + " de un total de " + total + " proveedores.");
            } else if (respuesta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "No se eliminará el proveedor " + prov + ".", "Proveedores", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void listar() {
        jTableProveedores.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        });
        TableRowSorter orden = new TableRowSorter(jTableProveedores.getModel());
        jTableProveedores.setRowSorter(orden);
    }

    private void mostrarPaginas() {
        int regPag = Integer.valueOf(jComboBoxRegistrosPagina.getItemAt(jComboBoxRegistrosPagina.getSelectedIndex()));
        int total = PROCON.total();
        int contador = 0;
        int result = 0;
        do {
            if (contador == 0) {
                result = total - regPag;
                jComboBoxPagina.addItem(String.valueOf(contador + 1));
                contador++;
            } else {
                result = result - regPag;
                jComboBoxPagina.addItem(String.valueOf(contador + 1));
                contador++;
            }
        } while (result > 0);
    }

    public void vaciarCampos() {
        jTextFieldNombreMantenimiento.setText("");
        jTextFieldPagina.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldDescuento.setText("");
        jTextFieldNoCliente.setText("");
    }

    private void asignarValores() {
        this.nombre = jTextFieldNombreMantenimiento.getText();
        this.email = jTextFieldCorreo.getText();
        this.web = jTextFieldPagina.getText();
        this.descuento = Double.valueOf(jTextFieldDescuento.getText());
        this.numCliente = Integer.valueOf(jTextFieldNoCliente.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxPagina;
    private javax.swing.JComboBox<String> jComboBoxRegistrosPagina;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelNoCliente;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreBuscar;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JLabel jLabelNumPagina;
    private javax.swing.JLabel jLabelPagina;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JPanel jPanelMantenimiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneProveedores;
    private javax.swing.JTable jTableProveedores;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldNoCliente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreMantenimiento;
    private javax.swing.JTextField jTextFieldPagina;
    // End of variables declaration//GEN-END:variables
}
